FROM python:3.13-bookworm

COPY --from=ghcr.io/astral-sh/uv:0.6.6@sha256:031ddbc79275e351a43cbb66f64d8cd314cc78c3878898f4ab4f147b092e8e2d /uv /uvx /bin/

WORKDIR /app


RUN apt-get update \
  && apt-get install -y --no-install-recommends libpq-dev gcc python3-dev libpq5 ca-certificates \
  && rm -rf /var/lib/apt/lists/*

ENV DBMATE_VERSION=v2.26.0

ADD --chmod=755 https://github.com/amacneil/dbmate/releases/download/${DBMATE_VERSION}/dbmate-linux-amd64 /bin/dbmate

