FROM python:3.13-bookworm@sha256:808883de855578fa0125bbf4442d81d290adea1d0156b8418d944c84c4ac55c9

COPY --from=ghcr.io/astral-sh/uv:0.6.2@sha256:01ddc2a91588f1210396433c79c9f58848ad668ea05bda895f5a1a31f2e5b64f /uv /uvx /bin/

WORKDIR /app


RUN apt-get update \
  && apt-get install -y --no-install-recommends libpq-dev gcc python3-dev libpq5 ca-certificates \
  && rm -rf /var/lib/apt/lists/*

ENV DBMATE_VERSION=v2.26.0

ADD --chmod=755 https://github.com/amacneil/dbmate/releases/download/${DBMATE_VERSION}/dbmate-linux-amd64 /bin/dbmate

