services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - ENABLE_OPENAPI=true
      - DATA_DIR=/data
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - ./data:/data
    env_file:
      - .env
  postgres:
    image: postgres:17@sha256:6efd0df010dc3cb40d5e33e3ef84acecc5e73161bd3df06029ee8698e5e12c60
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    command: postgres --log_statement=all

volumes:
  pg_data: