services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - ENABLE_OPENAPI=true
      - DATA_DIR=/data
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - ./data:/data
    env_file:
      - .env
  postgres:
    image: postgres:17@sha256:e6a4209d1a4893f2df3bdcde58f8926c3c929c4d51df90990ed1b36d83c1382a
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    command: postgres --log_statement=all

volumes:
  pg_data: