CREATE TABLE ingredients (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    ingredients JSONB NOT NULL
);

CREATE TABLE steps (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    steps JSONB NOT NULL
);

ALTER TABLE recipe ADD COLUMN ingredients_id BIGINT REFERENCES ingredients (id) ON DELETE CASCADE;
ALTER TABLE recipe ADD COLUMN steps_id BIGINT REFERENCES steps (id) ON DELETE CASCADE;