/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Instructions {
  id: string;
  position: number;
  recipe: string;
  text: string;
}

export interface Recipes {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: string;
  slug: string;
  title: string;
  updated_at: Generated<Timestamp>;
  user: string;
}

export interface DB {
  instructions: Instructions;
  recipes: Recipes;
}
