name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  # renovate: datasource=pypi depName=uv
  UV_VERSION: "0.7.1"
  # renovate: datasource=github-releases depName=amacneil/dbmate versioning=semver
  DBMATE_VERSION: v2.27.0

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-24.04
    container: python:3.13-bookworm@sha256:45d30477a740d9d20859029cf30d36bee188b20b5a5bb739095aeeef72d2a76d

    services:
      postgres:
        image: postgres:17@sha256:304ab813518754228f9f792f79d6da36359b82d8ecf418096c636725f8c930ad
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4 
      - uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6
        with:
          version: ${{env.UV_VERSION}}
      - run: uv python install
      - run: curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/download/${{env.DBMATE_VERSION}}/dbmate-linux-amd64 && chmod +x /usr/local/bin/dbmate
        name: Install dbmate
      - run: uv run pytest tests/repository
        env:
          DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable" 
          UV_LINK_MODE: "copy"
        name: Run tests
