name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  # renovate: datasource=pypi depName=uv
  UV_VERSION: "0.7.10"
  # renovate: datasource=github-releases depName=amacneil/dbmate versioning=semver
  DBMATE_VERSION: v2.27.0

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-24.04
    container: python:3.13-bookworm@sha256:5d0a64b7f8333d42568ae4076242d15dc22f0cb0ae26a1750cbb8a6570e48aa5

    services:
      postgres:
        image: postgres:17@sha256:6cf6142afacfa89fb28b894d6391c7dcbf6523c33178bdc33e782b3b533a9342
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4 
      - uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6
        with:
          version: ${{env.UV_VERSION}}
      - run: uv python install
      - run: curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/download/${{env.DBMATE_VERSION}}/dbmate-linux-amd64 && chmod +x /usr/local/bin/dbmate
        name: Install dbmate
      - run: uv run pytest tests/repository
        env:
          DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable" 
          UV_LINK_MODE: "copy"
        name: Run tests
