name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-24.04
    container: python:3.13-bookworm

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: potgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4 
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"
      - run: uv python install
      - run: uv run pytest 
      - run: uv run pytest -s  tests/repository
        env:
          DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable" 
