name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  # renovate: datasource=pypi depName=uv
  UV_VERSION: "0.6.17"
  # renovate: datasource=github-releases depName=amacneil/dbmate versioning=semver
  DBMATE_VERSION: v2.26.0

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-24.04
    container: python:3.13-bookworm

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4 
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{env.UV_VERSION}}
      - run: uv python install
      - run: curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/download/${{env.DBMATE_VERSION}}/dbmate-linux-amd64 && chmod +x /usr/local/bin/dbmate
        name: Install dbmate
      - run: uv run pytest tests/repository
        env:
          DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable" 
        name: run tests
